blank_issues_enabled: true
contact_links:
  - name: â“ Question
    url: https://jij-inc.slack.com/archives/C01FNJFD9FU
    about: Ask and answer questions about JijModeling on Slack
  - name: ğŸ”§ Troubleshooting
    url: https://jij-inc.slack.com/archives/C01FNJFD9FU
    about: Ask for help on Slack
  - name: ğŸ—£ Discussion
    url: https://jij-inc.slack.com/archives/C01FNJFD9FU
    about: Discuss development of JijModeling on Slack